language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: LD7DwH+5d6azxkUvxyWGwHYYmz2VM3thH+j46i9g4Kr9hZEzZPyd3W0OuLVIHy9UOHaqyeQDOTJbuZZ++zxUESneXtchlIkrNE8BOwn7IDxdj/vg3jV9ZCqn6GXkxr7ZfB9H1zdd9aLcQ8BPfH/vPpjfTkiJc8xSEiuqWuLaRzqMmt4QB/qPuoho6jDdGgJBYxg1vR1kEoOMacJsBiifauhKc4qFqAA3en6Rf6hokHVPNcYOaXhC9l0TSoWJN8ZfYbjabFY5SeDLwjgXLANrBPLA67GP6gb73n3XiDF9HDLyJ1br/kOmoFAVS4WJInVjYkpuhT675e6Yr3/mB+VDK2vOvGaxwObYpNFdjgVSEQJb+U2O3KR+kX0efBxnEgtLEWKjdgYKIQCUCYtSaYc8yT8MDmHwPkzhlM9DUqyWpbmozHX1LDYyFcofYjgWMIM0Hm8yKb6DGWAZ4hdy3KHpMgUBqE+2z8sblyLwPLO3J8sTYB83hmMJZclIMk8Oj8l4jPPNQtQMvl0S6DXbvnkWs4KRRBIojw7O9lkc+p4Rsw1nMg4VXtrw7cBrGcpeHQYQ3ZKhcbavt/vSPM8qc02yA5y2kEVUl91lG980Uv8ip2R7TxYwC1EBL+j6QagOAPh+fQRNpDsCAjTv8sNnjQdvf0zyxAeGckxnJcZkWd/EWWE=
  app: thomas-jonathan-fullstack-capstone
  on:
    repo: thinkful-c11/thomas-jonathan-fullstack-capstone
